### ISSUE TITLE
Add usage instructions?

### ISSUE THREAD

**Issue by alexellis** [grampelberg/linkerd2-mockups#1]
Would be nice to get usage instructions..

Running `python3 -m http.server` just got Safari to download all the files, it wasn't clear which file to look at.

`make` tried to run a sass binary, but that isn't on my system

How do I use this? 👍

**Comment by alexellis** [comment]
<img width="727" alt="Screenshot 2019-10-02 at 22 10 37" src="https://user-images.githubusercontent.com/6358735/66082208-8fe13400-e561-11e9-942c-ae6095c16187.png">
<img width="301" alt="Screenshot 2019-10-02 at 22 10 25" src="https://user-images.githubusercontent.com/6358735/66082209-8fe13400-e561-11e9-9361-8327fd59df12.png">

**Comment by grampelberg** [comment]
Ask and ye shall receive!
